### ISSUE TITLE
Can I lazy load remote Angular modules?

### ISSUE THREAD

**Issue by Alexzjt** [AndreiVajnaII/lazy-load-ng-modules#7]
I write an angular module demo_module by angular library. Then I run **ng build demo_module** to build it.
I get bundles such as demo_module.umd.js .
Can I lazy load demo_module from demo_module.umd.js?

**Comment by AndreiVajnaII** [comment]
I think this article can help you with that: https://www.angulararchitects.io/aktuelles/module-federation-light-using-microfrontends-with-angular-already-today/
